#!/bin/sh

case "$1" in
	install|upgrade)
		# Remove old installation files, if any 
		rm -rf /usr/share/vk4xmpp/library
		rm -rf /usr/share/vk4xmpp/crash
		rm -rf /usr/share/vk4xmpp/extensions
		rm -rf /usr/share/vk4xmpp/handlers
		rm -rf /usr/share/vk4xmpp/locales
		rm -rf /usr/share/vk4xmpp/gateway.py
		;;
esac
