#! /bin/bash
### BEGIN INIT INFO
# Provides:          vk4xmpp
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts VKontakte transport for Jabber
# Description:       starts VKontakte which provides a gateway that allows Jabber users to communicate with their
#                    contacts on VKontakte. It can connect to any Jabber server
#                    that supports the Connect component mechanism.  
### END INIT INFO


# /etc/init.d/vk4xmpp: start and stop VK4XMPP Transport service


export PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

NAME=vk4xmpp
DESC="VKontakte transport"
APPDIR="/usr/share/vk4xmpp"
PIDDIR="$APPDIR"
PIDFILE=$PIDDIR/vk4xmpp.pid
CONFIG_FILE="$APPDIR/Config.txt"
LOGFILE="$APPDIR/gateway.log"
USER=vk4xmpp
GROUP=vk4xmpp

DAEMON="/usr/bin/env python2"
OPTIONS="$APPDIR/gateway.py"

test -f "$(which python2)" || exit 0


case "$1" in
start)
        log_daemon_msg "Starting $DESC" "$NAME"
        sudo -b -u $USER $DAEMON $APPDIR/gateway.py > $LOGFILE 2>&1
        log_end_msg $?
        ;;
stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        #eval `kill $(cat /usr/share/vk4xmpp/pidFile.txt)`
        eval `kill -15 $(cat $PIDFILE)`
        log_end_msg $?
        ;;
status) 
        if [[ -f "$PIDFILE" ]]
        then
            APPPID=$(cat $PIDFILE)
            # fix: added | sed 's/^ *//g' # not obligatory from beginning of a line
            ps -eOcmd | sed 's/^ *//g' | grep ^$APPPID >&2
        else
            #echo "$PIDFILE does not exist" >&2
            PS=$(ps -eOcmd | grep gateway.py$)
            if [[ -n "$PS" ]]
            then
                echo "$PS" >&2
            else
                echo "$DESC $NAME stopped" >&2
            fi
        fi
        ;;
reload|force-reload)
        eval `kill -9 $(cat $PIDFILE)`
        $0 start
        ;;
restart)
        $0 stop
        $0 start
        ;;
*)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}" >&2
        exit 1
        ;;
esac

exit 0

# vim: filetype=sh
